### PR TITLE
Command line arguments for sanctioning

### PR DESCRIPTION
**Pull request by MattSScott**

### CODE REVIEW

**Comment by MattSScott** [comment]
A bit sloppy given the global values (subject to change), but given it's just us there's no need for getters/setters

**Review by antonypap — APPROVED** [review]
Changes look good, nice addition of json marshal. Things to keep in mind: 1) need to create `/output` beforehand for `.json` 2)  we now have both cmd line args  and the `.env` file

**Comment by MattSScott** [comment]
> Changes look good, nice addition of json marshal. Things to keep in mind: 1) need to create `/output` beforehand for `.json` 2) we now have both cmd line args and the `.env` file

1.) Very true. Can we push a commit that has this folder available?
2.) Yes, but the `.env` alone means that we can't automate simulation in, say, Python

**Comment by antonypap** [comment]
> > Changes look good, nice addition of json marshal. Things to keep in mind: 1) need to create `/output` beforehand for `.json` 2) we now have both cmd line args and the `.env` file
> 
> 1.) Very true. Can we push a commit that has this folder available? 2.) Yes, but the `.env` alone means that we can't automate simulation in, say, Python

1) done
2) its pretty easily accesible through a bash script, but i don't mind it tbh. Whatever you're most comfortable with

**Review by antonypap — APPROVED** [review]
LGTM

**Pull request merged**
